### ISSUE TITLE
undefined method `quoted_table_name' 

### ISSUE THREAD

**Issue by alec-c4** [laserlemon/vestal_versions#29]
Hi,
I've added your plugin to environment.rb and after attempt to run any rake task or script i see following error:

$ ./script/generate 
/opt/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/reflection.rb:187:in `quoted_table_name': undefined method`quoted_table_name' for VestalVersions::Tagging:Module (NoMethodError)
        from /opt/local/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations.rb:1416:in `configure_dependency_for_has_many'
        from /opt/local/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations.rb:824:in`has_many'
        from (eval):3:in `has_many'
        from /opt/local/lib/ruby/gems/1.8/gems/mbleigh-acts-as-taggable-on-1.0.5/lib/acts_as_taggable_on/acts_as_taggable_on.rb:25:in`acts_as_taggable_on'
        from /opt/local/lib/ruby/gems/1.8/gems/mbleigh-acts-as-taggable-on-1.0.5/lib/acts_as_taggable_on/acts_as_taggable_on.rb:24:in `class_eval'
        from /opt/local/lib/ruby/gems/1.8/gems/mbleigh-acts-as-taggable-on-1.0.5/lib/acts_as_taggable_on/acts_as_taggable_on.rb:24:in`acts_as_taggable_on'
        from /opt/local/lib/ruby/gems/1.8/gems/mbleigh-acts-as-taggable-on-1.0.5/lib/acts_as_taggable_on/acts_as_taggable_on.rb:20:in `each'
        from /opt/local/lib/ruby/gems/1.8/gems/mbleigh-acts-as-taggable-on-1.0.5/lib/acts_as_taggable_on/acts_as_taggable_on.rb:20:in`acts_as_taggable_on'

Can you tell me plz - what causes this error and how to solve?

**Comment by dtsadok** [comment]
This is a problem with acts-as-taggable-on, not vestal_versions...
(I think)

**Comment by dtsadok** [comment]
I resolved this by disabling tagging in the vestal_versions gem.  I took out the line:
include Tagging
from vestal_versions-1.0.2/lib/vestal_versions.rb, and deleted the file vestal_versions-1.0.2/lib/vestal_versions/tagging.rb

Not a problem for me since I don't plan on using tagging in VV, but still annoying since I have to do it on 3 different machines :-P

**Comment by ledermann** [comment]
It seems to be a naming conflict. Some has created a fork of vestal_versions to fix this: http://github.com/dfurber/vestal_versions. Hopefully this will be merged into the main repository.
