### ISSUE TITLE
undefined method `aliased_table_name'

### ISSUE THREAD

**Issue by HendrikRoth** [laserlemon/vestal_versions#73]
Rails 3.1.0rc5:

``` ruby
ruby-1.9.2-p290 :002 > @post.revert_to!(3)
   (0.5ms)  SELECT MAX("versions"."number") AS max_id FROM "versions" WHERE "versions"."versioned_id" = 6 AND "versions"."versioned_type" = 'Post'
   NoMethodError:   VestalVersions::Version Load (0.7ms)  SELECT "versions".* FROM "versions" WHERE "versions"."versioned_id" = 6 AND "versions"."versioned_type" = 'Post'
   undefined method `aliased_table_name' for #<ActiveRecord::Relation:0xac9fc5c>
   from     /home/hendrik/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.0.rc5/lib/active_record/relation.rb:454:in `method_missing'
   from /home/hendrik/.hendrikrvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.0.rc5/lib/active_record/associations/collection_proxy.rb:98:in `method_missing'
   from /home/hendrik/.hendrikrvm/gems/ruby-1.9.2-p290/bundler/gems/vestal_versions-6273df533f85/lib/vestal_versions/versions.rb:18:in `between'
   from /home/hendrik/.rvm/gems/ruby-1.9.2-p290/y-1.9.2-p290/bundler/gems/vestal_versions-6273df533f85/lib/vestal_versions/changes.rb:22:in `changes_between'
   from /home/hendrik/.rvm/gems/ruby-1.9.2-p290290/bundler/gems/vestal_versions-6273df533f85/lib/vestal_versions/reversion.rb:28:in `revert_to'
   from /home/hendrik/.rvm/gems/ruby-1.9.2-p290/bundler/gems//vestal_versions-6273df533f85/lib/vestal_versions/reversion.rb:38:in `revert_to!'
   from (irb):2
   from /home/hendrik/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.002.rc5/lib/rails/commands/console.rb:45:in `start'
   from /home/hendrik/.rbvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0.rc5/lib/rails/commands/console.rb:8:in `start'
   from /home/hendrik/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.0.9/s-3.1.0.rc5/lib/rails/commands.rb:40:in `<top (required)>'
   from script/rails:6:in `require'
   from script/rails:6:in `<main>'
```

**Comment by astjohn** [comment]
Confirmed for Rails 3.1.0rc6 as well.

**Comment by ichiro101** [comment]
I have written a fix for it, see https://github.com/laserlemon/vestal_versions/pull/75 It's rather simple

**Comment by astjohn** [comment]
@ichiro101, that's perfect.  Thanks!
