### ISSUE TITLE
VERSION is required

### ISSUE THREAD

**Issue by ghost** [laserlemon/vestal_versions#93]
Getting this error when trying to run down migrations:

``` bash
$ rake db:migrate:down 20130222000453 --trace
** Invoke db:migrate:down (first_time)
** Invoke environment (first_time)
** Invoke dotenv (first_time)
** Execute dotenv
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate:down
rake aborted!
VERSION is required
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@my-app/gems/activerecord-3.2.12/lib/active_record/railties/databases.rake:223:in `block (3 levels) in <top (required)>'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/Users/bm5k/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/bin/rake:19:in `load'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@global/bin/rake:19:in `<main>'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@my-app/bin/ruby_noexec_wrapper:14:in `eval'
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@my-app/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate:down
```

``` bash
$ bundle show vestal_versions
/Users/bm5k/.rvm/gems/ruby-1.9.3-p327@pp-cures/bundler/gems/vestal_versions-c7aa512666b2
```

Any idea what is causing this? The migration in question does not deal with a versioned model.

**Comment by laserlemon** [comment]
This has to do with how migrate:down works. The rake task requires a migration version to which to migrate. It has nothing to do with VV.

**Comment by ghost** [comment]
Interesting, because I am specifying a migration version.

Thanks for the feedback, I will poke around a bit more. Closing this until/unless I think it's a vestal_versions issue.
